const fs = require('fs').promises;
const glob = require('glob');

const srcDir = './src';
const targets = [
  'components',
  'functions',
  'mixins'
];

function createFile(name, files) {
  const importList = files.map(file => file.replace(/\.scss$/, ''))
    .map(file => `@import "./${file}";`)
    .join('\n');

  const data = `@charset "utf-8";
//
// DO NOT EDIT THIS FILE BY HAND - YOUR CHANGES WILL BE OVERWRITTEN
//
${importList}
`;

  return fs.writeFile(`${srcDir}/${name}.scss`, data, 'utf-8');
}

function generate(dir) {
  const matches = glob.sync(`${dir}/*.scss`, {cwd: srcDir});
  return createFile(dir, matches);
}

function createIndex() {
  return createFile('index', targets);
}

Promise.all(targets.map(generate))
  .then(createIndex)
  .then(() => {
    process.exit(0);
  })
  .catch((err) => {
    console.log(err);
    process.exit(1);
  });
