const fs = require('fs');
const glob = require('glob');

const targets = [
  'components',
  'mixins'
];

function createScss(matches) {
  return `@charset "utf-8";
//
// DO NOT EDIT THIS FILE BY HAND - YOUR CHANGES WILL BE OVERWRITTEN
//
${
  matches.map(file => file.replace(/\.scss$/, ''))
    .map(file => `@import "${file}";`)
    .join('\n')
}
`;
}

function generate(dir) {
  return new Promise((resolve, reject) => {
    glob(`./${dir}/*.scss`, (err, matches) => {
      if (err) {
        reject(err);
        return;
      }

      const data = createScss(matches);
      fs.writeFile(`./${dir}.scss`, data, 'utf-8', (err) => {
        err ? reject(err) : resolve();
      });
    });
  });
}

Promise.all(targets.map(generate))
  .then(() => {
    process.exit(0);
  })
  .catch((err) => {
    console.log(err);
    process.exit(1);
  });
